### ISSUE TITLE
Markers are jumping

### ISSUE THREAD

**Issue by pdwrl** [google-map-react/google-map-react#1143]
Hello.
Markers are jumping only when navigating the map by mouse.  They appears on their old places for a short time and then showing on a right places.
Strange: It doesn't reproduces on [Codesandbox](https://codesandbox.io/s/googlemapreact-demo-forked-hrqks5?file=/src/Map.js).

Any ideas please?

https://user-images.githubusercontent.com/5068644/188956432-226dae0c-c807-4bda-9115-841f49864777.mp4

**Comment by itsmichaeldiego** [comment]
@pdwrl Could you provide an example of your code, and which version of this library you're using?

**Comment by Exilent-aby** [comment]
@pdwrl @itsmichaeldiego  
I have forked @pdwrl 's codesandbox to use the new rendered for React 18. The markers can be seen jumping there.
[Link to the fork](https://codesandbox.io/s/googlemapreact-demo-forked-mbsis7?file=/src/index.js)
@pdwrl FYI: I changed the Index.js to this:
`
import React from "react";
import {createRoot} from "react-dom/client";
import SimpleMap from "./Map";
import { BrowserRouter, Link, Route } from "react-router-dom";
import "./styles.css";
const locations = require("./locations.json");

function App() {
  return (
    <div className="App">
      <SimpleMap locations={locations} />
    </div>
  );
}

const container = document.getElementById("root");
const rootElement = createRoot(container);
rootElement.render(<App/>);


`

**Comment by pdwrl** [comment]
@Exilent-aby yes, Your fork reproduces the jumping.
Thank You very much.

**Comment by EugeniaSSS** [comment]
I have the same problem! SOS

**Comment by adrian-koczen** [comment]
I agree, It would be nice to make this work again 😀

**Comment by Exilent-aby** [comment]
@pdwrl For now, I have downgraded to react 17 to make it work for my case. Personally, I don't want to move away from this library, as I found this to be the most straightforward approach to implementing google maps in react so far.

**Comment by pdwrl** [comment]
> downgraded to react 17

oh, I can't downgrade.
anyway, thank You so much.

**Comment by Exilent-aby** [comment]
This problem seems to be happening in many implementations of Google Maps with react. The official google map react wrapper (@googlemaps/react-wrapper) has [this  demo](https://googlemaps.github.io/react-wrapper/public/basic/)   listed in their documentation on [npmjs.com](https://www.npmjs.com/package/google-map-react). But they too seem to be using ReactDom.render with react 18 to make it work, at least this is what the console shows.
<img width="1679" alt="Screenshot 2022-09-12 at 12 41 48 PM" src="https://user-images.githubusercontent.com/49186221/189593912-5de3e02b-6795-44a5-ae6f-5315b05c06b7.png">

We might have to wait a little longer for this issue to be fixed.

**Comment by kkallasm** [comment]
Same problem here. Any updates?

**Comment by JonasRothmann** [comment]
Same problem. We use React 18 in production and can't downgrade.

**Comment by mcgrealife** [comment]
[This PR](https://github.com/google-map-react/google-map-react/pull/1146) by @viktorbezdek claims to solve it, but has been stale without review for 7 days now

**Comment by mcgrealife** [comment]
[A PR](https://github.com/google-map-react/google-map-react/pull/1146) by @bordeo addresses this, but needs review and approval

**Comment by giorgiabosello** [comment]
@mcgrealife the PR of @bordeo address issues with react 18, but I've found out that something else happens:
markers are not being reinitialized, so, or you can't see them on the map, since they have wrong style positions, or they move with the map.
I have tried to fix it, but it's like a matrioska. I'm implementing maps with the official library (@googlemaps/react-wrapper) since I cannot downgrade to react 17 too.

**Comment by Eslam3bed** [comment]
#### Experiencing the same issue when upgraded to react 18 `-_-`  
> When I turn the StrictMode on the app crashes 
![juming_markers](https://user-images.githubusercontent.com/20760072/194461181-d1886cb9-3976-4ab9-83cc-b33dbc9af8bc.gif)

**Comment by haabnaseem** [comment]
NextJS with React 18, same bug

**Comment by haabnaseem** [comment]
> NextJS with React 18, same bug

@pdwrl can you make your lat, lng values are present? i had one marker which was missing lng value and when I fixed that markers didn't jump anymore.

**Comment by Eslam3bed** [comment]
@haabnaseem Can you explain more, these details are mandatory, we do provide them, however, we still face the same issue,
can you explain more about your findings?
_Thanks_

**Comment by ilan-belfer** [comment]
React 18. Same bug

https://user-images.githubusercontent.com/96370537/195029680-d0cb7a35-36cf-4868-9f40-b60504a512d6.mp4

**Comment by mcgrealife** [comment]
@giorgiabosello ah I see.

The new google maps beta "[Advanced Markers](https://developers.google.com/maps/documentation/javascript/reference/advanced-markers)" look promising for most cases. I imagine these play well with the official [@googlemaps/react-wrapper](https://www.npmjs.com/package/@googlemaps/react-wrapper).

**Comment by giorgiabosello** [comment]
@mcgrealife at the end, I didn't use the official @googlemaps/reactwrapper, since it is only a wrapper that calls the API script. It doesn't accept markers as react components, but only the default one.
I've followed [this guide](https://dawchihliou.github.io/articles/building-custom-google-maps-marker-react-component-like-airbnb-in-nextjs).

**Comment by AndreiFVPopa** [comment]
Hey there guys. 
I've been struggling with this bug a lot also. It definitely needs a fix asap. 
I temporarily found a workaround this one. I used an opacity state transition. With the help of drag and dragend, I managed to hide the dots while the flickering is happening.
`const [opacity, setOpacity] = useState(1)
...
<GoogleMapReact
onDrag={() => setOpacity(0)}
        onDragEnd={() => setOpacity(1)}
        >
        <Marker style={{opacity: opacity}}>1</Marker>
        </GoogleMapReact>`

**Comment by yakushstanislav** [comment]
Same problem.

**Comment by xwg2015** [comment]
Same problem.

**Comment by Naught0** [comment]
Any word on what's causing this? Why does reverting to react 17 fix it?

**Comment by giorgiabosello** [comment]
> Any word on what's causing this? Why does reverting to react 17 fix it?

@Naught0 because React 18, in developer mode, mount and unmount the component to make some tests.

**Comment by Gigiz** [comment]
> > Any word on what's causing this? Why does reverting to react 17 fix it?
> 
> @Naught0 because React 18, in developer mode, mount and unmount the component to make some tests.

Nope, i tried in production mode but this behaviour still present

**Comment by JavierSolis** [comment]
You can use the parameter onGoogleApiLoaded, to have the reference to the map and add the markers, these markers will not have the problem

```
. . . 
const renderPolylines =  (map, maps) => {
        //places is an object array with latitude and longitude
        places.map(place => {
            new maps.Marker({
                position: {
                    lat: place.lat,
                    lng: place.lng,
                },
                map,
            });})

        var bounds = new maps.LatLngBounds()
        for (let place of places) {
            bounds.extend(
                new maps.LatLng(place.lat, place.lng)
            )
        }
        map.fitBounds(bounds)
    }

. . .
<GoogleMapReact
                    bootstrapURLKeys={{key: "API_KEY"}}
                    defaultCenter={location}
                    defaultZoom={zoomLevel}
                    onGoogleApiLoaded={({map, maps}) => renderPolylines(map, maps)}>

. . .

```

**Comment by giorgiabosello** [comment]
I've made a repository myself which is working with React 18. I've abandoned this one, since it seems it is not maintained anymore.
[LINK](https://github.com/giorgiabosello/google-maps-react-markers)

**Comment by alehano** [comment]
> I've made a repository myself which is working with React 18. I've abandoned this one, since it seems it is not maintained anymore. [LINK](https://github.com/giorgiabosello/google-maps-react-markers)

Thanks, finally it's working

**Comment by sukhovv** [comment]
> I've made a repository myself which is working with React 18. I've abandoned this one, since it seems it is not maintained anymore. [LINK](https://github.com/giorgiabosello/google-maps-react-markers)

What about draggable markers in there? Looks like it is not supported in the same way with `draggable` + `onChildMouseUp` + `onChildMouseMove` props

**Comment by sukhovv** [comment]
> I've made a repository myself which is working with React 18. I've abandoned this one, since it seems it is not maintained anymore. [LINK](https://github.com/giorgiabosello/google-maps-react-markers)

@giorgiabosello What about draggable markers in there? Looks like it is not supported in the same way with draggable + onChildMouseUp + onChildMouseMove props

**Comment by giorgiabosello** [comment]
> > I've made a repository myself which is working with React 18. I've abandoned this one, since it seems it is not maintained anymore. [LINK](https://github.com/giorgiabosello/google-maps-react-markers)
> 
> @giorgiabosello What about draggable markers in there? Looks like it is not supported in the same way with draggable + onChildMouseUp + onChildMouseMove props

Not managed, if you want to help with a PR, it's appreciated :)

**Comment by neo0910** [comment]
@itsmichaeldiego

Hello, I have this problem on my project (React 18, google-map-react 2.2.0). Will the PR of [bordeo](https://github.com/bordeo) be merged?

**Comment by giorgiabosello** [comment]
@neo0910 this PR fixes some things, but breaks some others.
If you don't need everything that's supported in this library, check [Google Maps React Markers](https://github.com/giorgiabosello/google-maps-react-markers).

**Comment by Lamanris** [comment]
2023, the bug still exists

**Comment by Lamanris** [comment]
> I've made a repository myself which is working with React 18. I've abandoned this one, since it seems it is not maintained anymore. [LINK](https://github.com/giorgiabosello/google-maps-react-markers)

Thank you!

**Comment by anabel29** [comment]
Same issue :( any updates?

**Comment by rushan-bp** [comment]
Same Issue

**Comment by rushan-bp** [comment]
import React from 'react';
import ReactDOM from 'react-dom';
import { CssVarsProvider } from '@mui/joy/styles';
import { PersistGate } from 'redux-persist/integration/react';
import { Provider } from 'react-redux';
import { persistor, store } from 'tools/store';
import theme from 'tools/theme';
import App from './App';
import reportWebVitals from './reportWebVitals';
import { BrowserRouter } from 'react-router-dom';
import './styles.css';

ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <CssVarsProvider theme={theme}>
            <App />
          </CssVarsProvider>
        </PersistGate>
      </Provider>
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById('root')
);


use this in your index.tsx/js it will act as react 17 and fix this bug

**Comment by sukhovv** [comment]
@itsmichaeldiego great to know the library is still alive.
any chance this issue will be fixed?

**Comment by Mu-Aleem** [comment]
same issue when i drap the map my current location marker moves.  how can i fix this i,m using the react 18 and google-map-react

**Comment by giorgiabosello** [comment]
Guys, there isn't a fix for this issue. It is how React18 works on developer mode.
You shouldn't have problems in production mode. 
This library needs to be completely rewritten to work with R18+, I tried to to fix it but it was like a matrioska problem, so I coded from zero a library.
[Google Maps React Markers](https://github.com/giorgiabosello/google-maps-react-markers)

**Comment by Mu-Aleem** [comment]
@giorgiabosello what do you suggest?  I want to add the map the same as Uber.

**Comment by Mu-Aleem** [comment]
> Guys, there isn't a fix for this issue. It is how React18 works on developer mode. You shouldn't have problems in production mode. This library needs to be completely rewritten to work with R18+, I tried to to fix it but it was like a matrioska problem, so I coded from zero a library. [Google Maps React Markers](https://github.com/giorgiabosello/google-maps-react-markers)

what do you suggest? I want to add the map the same as Uber.

**Comment by giorgiabosello** [comment]
> > Guys, there isn't a fix for this issue. It is how React18 works on developer mode. You shouldn't have problems in production mode. This library needs to be completely rewritten to work with R18+, I tried to to fix it but it was like a matrioska problem, so I coded from zero a library. [Google Maps React Markers](https://github.com/giorgiabosello/google-maps-react-markers)
> 
> what do you suggest? I want to add the map the same as Uber.

@Mu-Aleem there isn't much you can do:
- keep this library and use it only on developer mode
- code from zero another one, using Google Maps API
- use mine (mentioned above) and integrate with a PR what you think is missing and should be available to everyone.

**Comment by rise2vados** [comment]
> Guys, there isn't a fix for this issue. It is how React18 works on developer mode. You shouldn't have problems in production mode. This library needs to be completely rewritten to work with R18+, I tried to to fix it but it was like a matrioska problem, so I coded from zero a library. [Google Maps React Markers](https://github.com/giorgiabosello/google-maps-react-markers)

giorgiabosello, first of all, thank you for using google-maps-react-markers. Everything works well without any jumps or flickers, but I have a need to change the center of the map after clicking on a marker. How can I achieve this? Thank you once again.

**Comment by giorgiabosello** [comment]
@rise2vados this isn't the right thread. There's a discussion in the repository asking the same thing. Check there and you'll find your answer. :)

**Comment by yusufkhaled-DC** [comment]
> I've made a repository myself which is working with React 18. I've abandoned this one, since it seems it is not maintained anymore. [LINK](https://github.com/giorgiabosello/google-maps-react-markers)

You're amazing!!! Thank you so much

**Comment by hoangviet1807** [comment]
Any updates???

**Comment by HelloNeptune** [comment]
> Any updates???

[It](https://github.com/google-map-react/google-map-react/issues/1197#issuecomment-1779040672) this may help, give a try

**Comment by karimtamerBW** [comment]
Any new updates please?

**Comment by stevengrimaldo** [comment]
still an issue 2024 even though their last release says supporting react 18, so i dont think react 18 had anything to do with it maybe @giorgiabosello.

**Comment by giorgiabosello** [comment]
> still an issue 2024 even though their last release says supporting react 18, so i dont think react 18 had anything to do with it maybe @giorgiabosello.

Yes, it does! Because it mounts and remounts the components, and the library doesn't work. It's old.

**Comment by stevengrimaldo** [comment]
> > still an issue 2024 even though their last release says supporting react 18, so i dont think react 18 had anything to do with it maybe @giorgiabosello.
> 
> Yes, it does! Because it mounts and remounts the components, and the library doesn't work. It's old.

the library is old yes, the library works but still has the jumpiness as you mentioned.

**Comment by Hosar** [comment]
2024, and still the same problem 🫠
Thanks @giorgiabosello  for your solution 👍

**Comment by DoHue97** [comment]
Hi All,
i have an issue when i drag end on map, i have only a marker, but it's jumping other location when i drag end. Any one help me to this issue?

https://github.com/google-map-react/google-map-react/assets/39371953/f1c23808-5b6f-4738-b652-7795379c1873


"react": "^17.0.2",
"google-map-react": "^2.1.10",

and here are the code files: 
1. used the components
![image](https://github.com/google-map-react/google-map-react/assets/39371953/a57367c0-257d-4a91-b6b3-60528ac9c06e)
2. Custom Google Map
![image](https://github.com/google-map-react/google-map-react/assets/39371953/9e0b738a-afee-43f8-a437-388c3921f774)
3. Custom Marker
![image](https://github.com/google-map-react/google-map-react/assets/39371953/047b60d5-7e06-480c-8efe-6bd2830d1f05)

**Comment by pklingman** [comment]
In case anyone following this issue missed it, https://github.com/google-map-react/google-map-react/pull/1224 is the fix that was merged for this.
