### ISSUE TITLE
onChildClick Working on Desktop/iOS but not Android

### ISSUE THREAD

**Issue by oscarwong67** [google-map-react/google-map-react#516]
Very recently I've been having a bug with my web application (despite not updating it at all), where my rendered markers on the map don't trigger click events anymore, but ONLY on Android - I've tested this on mobile devices and using Chrome's device emulator. 

onChildClick doesn't do anything on Android (when I set onChildClick to just a console.log, and then you click on a marker on the map, it'll respond accordingly for desktop or iOS but NOT on Android - it does nothing). Any insight?

Edit: I've now tested on Firefox's emulators and it works just fine on both iOS and Android. That said, it still doesn't work on mobile (firefox or chrome on Android doesn't work)

Edit #2: I reinstalled/updated the package, along with a few other packages (Onsen-UI and react-image-resizer, which I use to places images as the markers), and now it doesn't work on Chrome's iOS emulator either.

**Comment by thiagoterleski** [comment]
I'm having this same issue on mobile versions, the mouse click event and mouseover are not working, you can check the online examples using chrome mobile preview when you open for the first time is working but if you refresh and try to click on pins, **it not works**:

![istarkov github io_google-map-react_map_main_ iphone 8 plus](https://user-images.githubusercontent.com/2950918/36401043-9b0468ce-1589-11e8-9893-46427482995e.png)

**Comment by experimatt** [comment]
I'm having a similar problem where clicking on markers on the map works fine on desktop, but doesn't work on iOS/Android.

I believe something changed recently in Google Maps' Javascript API, but I don't know exactly how this library interacts with it. More details here: https://developers.google.com/maps/documentation/javascript/releases

**Comment by experimatt** [comment]
OK - I've got a hacky temporary solution to this problem. Append `&v=3.31` to your google maps API key when you're setting `bootstrapURLKeys` on the `<GoogleMapReact>` component.

This will both fix map clicking behavior on mobile, and also revert back to the original base map. But this is only temporary. A better solution would be to implement a way to pass in the google maps API version as a prop within the `<GoogleMapReact>` component.

**Background info**
Google [just updated](https://developers.google.com/maps/documentation/javascript/releases#332) the Google Maps Javascript API to use an experimental renderer and base map, which I believe are what's causing this problem.

Per Google, you can [opt-out](https://developers.google.com/maps/documentation/javascript/basemap#how-to-opt-out) of using the experimental renderer and base map by appending `&v=3.31` after your API key.

**Comment by oscarwong67** [comment]
@experimatt I can confirm that the fix definitely works, so for now we know it's on Google's end.

**Comment by stephenfarrar** [comment]
Google has fixed this issue now in v=3.32
Can you try again and confirm?

**Comment by oscarwong67** [comment]
@stephenfarrar I can confirm that the issue has been fixed, BUT - when I switched from 3.31 to 3.32 (which introduced this issue) another problem arose that when you zoom into the map, the markers "teleport" before going back to their original location. This has NOT been fixed, but the issue I originally raised has been fixed. Personally, I'll be sticking with 3.31 for a while.

**Comment by experimatt** [comment]
@oscarwong67 +1 I just tested it and experienced the same thing.

If clicks are working `onChildClick` now, but the markers are still teleporting, should we close this issue and open a new one for the teleportation thing?

**Comment by jseremba** [comment]
Help needed, the way `onChildClick ` works, with these kind of markers, its only the lower part of the marker that is clickable, the upper part is not
![map-marker-icon](https://user-images.githubusercontent.com/8972657/41361682-512535ae-6f38-11e8-8502-e4d04ab06186.png)

**Comment by oscarwong67** [comment]
@jseremba could you move the marker slightly below where you want it? But that means it's coordinates would be off. You could shrink it too, I guess. I can't think of anything else since you can't move the centre

**Comment by itsmichaeldiego** [comment]
@oscarwong67 @experimatt Sorry I just come across this issue, the problem that the markers "teleport" before going back to their original location has been fixed for latest release of Google maps. Let me know if its working for you now.

**Comment by itsmichaeldiego** [comment]
@jseremba That is a great observation, could you create a new issue and provide a codepen that reproduces the error? I will take a look as soon as possible.

**Comment by experimatt** [comment]
@oscarwong67 @itsmichaeldiego I believe the teleporting map markers bug is still an issue and just created a separate issue for it: https://github.com/google-map-react/google-map-react/issues/636
