### ISSUE TITLE
google-map-react now load google maps api all the time even if a key  is not provided

### ISSUE THREAD

**Issue by stunaz** [google-map-react/google-map-react#954]
**Describe the bug 🐛**

I use this lib, but I manually load the google maps api.
now i just found out that the lib is loaded multiple time:

> You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.

Using latest version

**Comment by stunaz** [comment]
I can confirm that the behavior changed after version `2.1.3`.
`2.1.3` is fine...

**Comment by longprao** [comment]
Confirmed this issue, I have even followed this instruction but still couldn't fix it:

https://github.com/wellyshen/use-places-autocomplete/issues/107#issuecomment-683162018

I upgraded from 1.1.7 so not sure which version caused it, but I have reverted to 1.1.7 for now. But after digging in the source I think it's due to `@googlemaps/js-api-loader` library introduced in 2.1.5.

I tried this library in my code to load google manually and also had that issue.

**Comment by itsmichaeldiego** [comment]
Hey folks, I am sorry you're facing this issue, seems that it was introduced [here](https://github.com/google-map-react/google-map-react/pull/942/files#r499144010) by @jpoehnelt and I dragged it to my PR https://github.com/google-map-react/google-map-react/pull/946. I asked @jpoehnelt to see if he had any reason to remove it but I will go ahead and release a patch to see if that solves the problem!

**Comment by itsmichaeldiego** [comment]
I released this in `2.1.7`

**Comment by itsmichaeldiego** [comment]
@stunaz @longprao Waiting for the confirmation 👍 Thanks in advance.

**Comment by longprao** [comment]
@itsmichaeldiego thanks for the quick fix, however I'm sorry it still doesn't work for me. I have tried reinstalling multiple times between v2 and v1, and only on v1 (1.1.7), it works for my Next JS app. I put the script in the header like this:

```
import Head from 'next/head';

...
<Head>
    ...
    <script src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GMAPS_API}&libraries=places`} />
  </Head>
...
```

**Comment by itsmichaeldiego** [comment]
@longngn Why don't you let google map handle this? 

```JSX
<GoogleMap 
  bootstrapURLKeys={{
    key: process.env.NEXT_PUBLIC_GMAPS_API,
    libraries: ['places'],
  }}
/>
```

**Comment by itsmichaeldiego** [comment]
Ok, could you guys provide a codesandbox so its easier for me to check? Or a repo I can run?

**Comment by longprao** [comment]
@itsmichaeldiego I need to use `google.maps.places.Autocomplete` in different pages and components that does not have google map react. Do you have instructions to always load gmaps api in every page (or any page that I want)?

**Comment by stunaz** [comment]
Hi @itsmichaeldiego, please reopen.
its not working... a simple codesanbox would be a simple example without the key provided, and the google script should not be loaded.

here is the sandbox https://codesandbox.io/s/cool-bash-cebm8?file=/src/App.js

if you inspect the url https://cebm8.csb.app/ you will see that it's still loading the google map

![image](https://user-images.githubusercontent.com/1305483/95082686-6c5b4700-06e9-11eb-95e9-56edd08bf7dd.png)

**Comment by tmilciunas** [comment]
Can confirm, this also happens to me with `v2.1.7`. I am using `google-map-react` for `map` loading and loading `autocomplete` with google API through a script. Although `v2.1.3` is also throwing an exception that `Google Maps JavaScript API multiple times on this page`.

**Comment by itsmichaeldiego** [comment]
Folks, I think this is a problem with the new library we're using to load the script: https://github.com/googlemaps/js-api-loader , I thought this was being handled by them but seems that it is not. 

This was introduced in https://github.com/google-map-react/google-map-react/pull/942 when we removed these lines [L37-L49](https://github.com/google-map-react/google-map-react/pull/942/files#diff-9a6a99e7dbcf49926535aa0d9547c3a0L37-L49).

I contacted @jpoehnelt who is the dev from google that created this PR and also the loader library. If he doesn't answer soon I will just rollback these changes and release a patch.

**Comment by jpoehnelt** [comment]
The issue is that the loader is reinstantiated multiple times. This differs from the pr I had submitted in https://github.com/google-map-react/google-map-react/pull/942/files#diff-9a6a99e7dbcf49926535aa0d9547c3a0R3.

In version 1.4.0 of @googlemaps/js-api-loader, it now also allows an id attribute to be added to the script tag and looks for that before adding another. A default id is used and should prevent any multiple loads.

So I suggest one or both of:
1. upgrade to 1.4.0
1. use single instance of Loader https://github.com/google-map-react/google-map-react/pull/942/files#diff-9a6a99e7dbcf49926535aa0d9547c3a0R3

**Comment by itsmichaeldiego** [comment]
Thanks @jpoehnelt, I didn't know that line was meant for that, I will go ahead and merge your PR https://github.com/google-map-react/google-map-react/pull/958

**Comment by itsmichaeldiego** [comment]
I've released this in `2.1.8`, please let me know if it is working!

**Comment by morgoth** [comment]
@itsmichaeldiego 2.1.8 didn't fix it for me. There is still the same issue.

**Comment by itsmichaeldiego** [comment]
@morgoth Thanks for letting me know. Let's wait for @jpoehnelt answer but I think the best way to go might be to _use a single instance of Loader_, and see if that fixes the problem.

**Comment by rostgoat** [comment]
Is it safe to use this npm package at the moment, despite the error @itsmichaeldiego  @jpoehnelt ?

**Comment by cp-ankush** [comment]
@itsmichaeldiego I am still facing the same issue in latest v2.1.8

**Comment by itsmichaeldiego** [comment]
I have been waiting for an answer from @jpoehnelt !

**Comment by itsmichaeldiego** [comment]
@rostgoat Yes, it is totally safe, this is just a warning and it affects the people who uses multiple instances of GMaps. Also, fixing to version `1.1.4` fixes the issue

**Comment by jpoehnelt** [comment]
So it seems the issue is that google.maps is already defined and this component previously had logic to only load if it was not defined. 

The following https://github.com/google-map-react/google-map-react/pull/946/files#diff-d80e5099ab1e9d5c62c83fa52807f55af66639fee1e3e0065fcd723a56aea22aL37 branch should not have been removed. I can move this logic to `@googlemaps/js-api-loader` too.

**Comment by jpoehnelt** [comment]
I have a fix in https://github.com/googlemaps/js-api-loader/pull/81 but this should probably be fixed here with an option to not load the google maps script because the application needs to be responsible for only loading the API once and avoiding inconsistencies in the script params(key, library, channel, etc).

**Comment by jpoehnelt** [comment]
https://www.npmjs.com/package/@googlemaps/js-api-loader/v/1.7.0 will not add another script tag, but it will still raise a warning in console.

**Comment by itsmichaeldiego** [comment]
@jpoehnelt I agree, I am sorry I removed that, but it wasn't stated what was being used for. Would you like to submit a PR adding that change? I can release it quickly

I agree with you that we should fix this in both sides. So I would say that we add that previous logic, and also update the `js-api-loader`

**Comment by itsmichaeldiego** [comment]
Hey everyone, I released patched version `2.1.9`, let me know if its working.

CC @jpoehnelt @cp-ankush @rostgoat @morgoth @tmilciunas @longprao @stunaz

**Comment by longprao** [comment]
@itsmichaeldiego thanks, it works! I no longer have the message "multiple times..." anymore.

Now I get only this warning but it's not a problem:

> Aborted attempt to load Google Maps JS with @googlemaps/js-api-loader.This may result in undesirable behavior as script parameters may not match.

**Comment by morgoth** [comment]
The same as @longprao wrote. It works with `Aborted attempt to load Google Maps JS with @googlemaps/js-api-loader.This may result in undesirable behavior as script parameters may not match` warning.
Isn't it something that should be somehow fixed?

**Comment by rostgoat** [comment]
I still see the error after updating to `2.1.9`

```
You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors
```

I know also see the same error that @longprao is seeing

**Comment by itsmichaeldiego** [comment]
Clearly this is not the fix, and the google api loader is not working as expected, @jpoehnelt what now?

**Comment by jpoehnelt** [comment]
There is nothing in the @googlemaps/js-api-loader causing the failure. The case documented by @morgoth is that this component is telling `@googlemaps/js-api-loader` to load but the there is no key prop being passed.

Is there some expectation that if no key is provided the component will not load google maps? From my response a couple days ago:

> this should probably be fixed here with an option to not load the google maps script because the application needs to be responsible for only loading the API once and avoiding inconsistencies in the script params(key, library, channel, etc).

As to the case with @rostgoat, etal with `You have included the Google Maps JavaScript API multiple times on this page...` more information is needed and ideally a minimally reproducible example. Are there other components that might be loading google maps? Is there a `<script>` tag loading google maps? 

Note that anyone that gets the following:

>Aborted attempt to load Google Maps JS with @googlemaps/js-api-loader. This may result in undesirable behavior as script parameters may not match.

These messages are due to application developers having multiple ways google maps is being added to the page. From what I can tell this is not a problem with the component here. This must(and should) be fixed by the application developer.

**Comment by itsmichaeldiego** [comment]
@jpoehnelt Thanks for your answer, because the loader logic is the same than before I assumed it was on the loader end. 

About the key: we always allowed users to render the map without providing a key, where it enters in developer mode.

@morgoth could you provide a live example reproducing it?

**Comment by morgoth** [comment]
it's something like this:
```
<GoogleMapReact
  bootstrapURLKeys={{ client: 'my-client' }}
  defaultCenter={center}
  defaultZoom={ZOOM}
  options={{ styles: MAP_STYLES }}
  yesIWantToUseGoogleMapApiInternals
  onGoogleApiLoaded={({ map, maps }) => handleApiLoaded(map, maps)}
/>
```
and then we use `maps.DirectionsService` and `maps.DirectionsRenderer` to draw some routes.

Sorry for example. I cannot easily extract the working code.

**Comment by itsmichaeldiego** [comment]
@morgoth Why aren't you providing a key though? Are you not using it in prod env? You can get one for free.

**Comment by morgoth** [comment]
I'm providing a `client` which is another way of authentication https://developers.google.com/maps/premium/overview#authentication-and-authorization

**Comment by jino-grazitti** [comment]
Hi @itsmichaeldiego,

I am using "google-map-react" in one of the components and the site already has a google map API loaded for other functionalities like autocomplete in some of the components. Now when the "google-map-react" component loads it initiates the google-map-API loader and throws the following warning:

"_Google Maps already loaded outside @googlemaps/js-api-loader.This may result in undesirable behavior as options and script parameters may not match._"

So just wanted to confirm is this just a warning and can be ignored? or can this affect any of the site operations?

Any help or suggestions would be really appreciated!
Thanks

**Comment by jpoehnelt** [comment]
This warning comes from @googlemaps/js-api-loader. It may be safe to ignore if the api was loaded correctly the first time.

**Comment by apeTrackunit** [comment]
Hi @jpoehnelt,

I'm using "google-map-react" in multiple components and we have an option to change the app language that I also use as a parameter in useJsApiLoader. When some user change the language, the app'll crashed because of [these lines](https://github.com/googlemaps/js-api-loader/blob/b0ef634050eabf0db97e26a6735b4d64cde72725/src/index.ts#L288) -> "Loader must not be called again with different options".

Is there any way how I can force it to reload the map?

Thanks

**Comment by jpoehnelt** [comment]
Changing the language is not supported and will result in double billing. To avoid that issue, all of window.google should be removed and the loader reset(see https://github.com/googlemaps/js-api-loader/issues/210).

**Comment by co-dax** [comment]
@jpoehnelt ...and how do we reset loader? I couldn't find that information at [https://github.com/googlemaps/js-api-loader/issues/210](url)

**Comment by hugoh59** [comment]
Is there a fix for this issue ? suddenly started happening on my side.
