### ISSUE TITLE
Map markers wiggling around whilst moving map

### ISSUE THREAD

**Issue by dionkas** [google-map-react/google-map-react#998]
Hey, I have the following marker:
Using semantic-ui for icons.

```
export default function MapMarker() {

  return (
    <div}>
      <Popup
        position="top center"
        trigger={
          <Icon
            name="map marker alternate"
            className="map-marker"
            color="purple"
          />
        }
      />
    </div>
  );
}
```

and the following css applied to the class "map-marker"

```
.map-marker {
  top: 50%;
  left: 50%;
  transform: translate(-50%, -100%);
  cursor: pointer;
}
```

Using the above css i solve the problem of markers moving whilst zooming out. But they are wiggling, moving slightly just a bit like by 1mm each time I drag the map to move it in any direction.

Where us in this [example](https://google-map-react.github.io/google-map-react-examples/?path=/story/main-examples--base)

the markers don't move at all. I have also tried using the same marker and css from the example above.

Any help?

**Comment by karldanninger** [comment]
I've seen this issue pop in the last couple of weeks. I don't believe this issue originates with this library, but Google's Javascript API somehow. I'll be on the lookout for a solution to this as well.

**Comment by dionkas** [comment]
Thank you! The behaviour should be what your example is doing at: https://google-map-react.github.io/google-map-react-examples/?path=/story/main-examples--base

**Comment by karldanninger** [comment]
Eek! I'm silly. I should've known this! @dionkas can you confirm your browsers zoom level is set to default/100% ?

**Comment by dionkas** [comment]
@karldanninger Yes it is! But the map is inside a container on my page. (not 100% width and height)

**Comment by c0d3rvik** [comment]
I am also having same problem. when I render markers and move map markers seems to double

**Comment by camro** [comment]
Have you tried `transform: translate(-50%, -50%);`?

**Comment by jonesne92** [comment]
Has there been any update on this, or any workaround suggested? I'm getting the same issue

**Comment by itsmichaeldiego** [comment]
@jonesne92 @dionkas Are you using the latest version of google-map-react? We've fixed this already

**Comment by dionkas** [comment]
@itsmichaeldiego I updated this morning. Wiggling still persists. 
My code is as follows:

Map marker

```
          <img
            className="map-marker"
            style={{ width: 35, height: 35 }}
            alt="map marker"
          />
```

Css

```
.map-marker {
  position: absolute;
  top: 50%;
  left: 50%;
  /*transform: translate(-50%, -50%);*/
  transform: translate(-50%, -100%);
  cursor: pointer;
  outline: none;
}
```

**Comment by jonesne92** [comment]
@itsmichaeldiego I've also updated to 2.1.10 and am still seeing the wiggling. I also see it on the main example at https://google-map-react.github.io/google-map-react/map/main/

**Comment by jricaldi** [comment]
Hey guys. For everyone who has the same nightmare. Use the api approach https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/MarkerInfoWindowGmapsObj.js it works finally.
